services:
  _defaults:
    public: true

  react.amqp:
    class: Morbo\React\Amqp\Service\Amqp
    arguments: ["@service_container", "@react.loop", "connectionParams"]

  Morbo\React\Amqp\Service\Amqp: '@react.amqp'